### ISSUE TITLE
changing directory of image and compilation

### ISSUE THREAD

**Issue by davctv** [jkearins/ESP32_mkfatfs#3]
Hi,

I would like to change the default mount directory from "/spiflah" to "/root". I checked that on main.cpp it is defined 

static const char *BASE_PATH = "/spiflash";

That's good. 

I would like to know how to compile for windows (I use mingw32) the new mkfatfs.exe

Thanks

**Comment by jkearins** [comment]
To rebuild mkfatfs.exe use command:
`make mkfatfs
`

**Comment by davctv** [comment]
Thanks, that worked!

Really impressed about this tool..very usefull
