### ISSUE TITLE
maximum number of files for image

### ISSUE THREAD

**Issue by davctv** [jkearins/ESP32_mkfatfs#4]
Hi,

Sorry to chase you today..

I'm trying to build a fat image composed of 2 directories, each of one consisting of 500 files for a total of less than 200KB. My fat size is 1MB.

When I run
`make makefatfs`

at some point (it seems after 241 files of the first directory I got)

`
adding to image: /users/1946487.tel
error: failed to open "/root/users/1946487.tel" for writing
`

If I sent you the two folders can you try to check if it a problem of size or is there a limitation of the tool?

Attached there are two image: one is working with 241 files on one folder and 141 files on the other..
The other image is not working and it has 500 files on each folder.

Thanks
[image.zip](https://github.com/jkearins/ESP32_mkfatfs/files/1530874/image.zip)
[image_working.zip](https://github.com/jkearins/ESP32_mkfatfs/files/1530875/image_working.zip)

**Comment by jkearins** [comment]
Hi, @davctv,
For your file of length 300 bytes fatfs allocates 1 cluster, 4096 bytes. If image is 1Mb than you can store ~256 files. Setting cluster size to 512 will increase file count by 8 times (256->2048 files). I will try to find a way to set cluster size to 512.

**Comment by davctv** [comment]
Thanks @jkearins.
It could be very usefull to setup the cluster size (I guess in power of 2) as a define in mkfatfs source code so one can choose the best size for its purpose.

**Comment by jkearins** [comment]
I updated repository, now you can define your own sector_size/cluster_size but I think that minimal values are good for most cases. The definitions are located in /components/mkfatfs/src/fatfs/fatfs.c:
```
#define MY_ALLOCATION_UNIT	512	// define sector size, valid values: 512, 1024, 2048, 4096
#define MY_CLUSTER_SIZE		(MY_ALLOCATION_UNIT * 1)	// define cluster size as sector size multiplied by 1,2,4,8

```

**Comment by davctv** [comment]
Thank you @jkearins 
I think 512 byte should be enough..
