### ISSUE TITLE
image file seems have wrong content

### ISSUE THREAD

**Issue by Jacques-Zhao** [jkearins/ESP32_mkfatfs#5]
Hi, @jkearins , when I run the command 'make makefatfs', I get  the correct image. But when i mount the image file, i found the file name was correct, but the content confused.

**Comment by jkearins** [comment]
How you mount the image file?

**Comment by Jacques-Zhao** [comment]
Hi   just open with disk image mounter.  I found the name and size of these files is right, but the content is wrong.
![mountfile](https://user-images.githubusercontent.com/15244200/34140087-4e7a2310-e4b3-11e7-8ce0-8f319b7bd598.jpg)

Another problem, I found when i mount server times, I will cannot mount again, here is the log:

`rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:3884
load:0x40078000,len:0
load:0x40078000,len:12988
entry 0x40078d8c
I (109) cpu_start: Pro cpu up.
I (109) cpu_start: Starting app cpu, entry point is 0x40080ed4
I (0) cpu_start: App cpu up.
I (110) heap_init: Initializing. RAM available for dynamic allocation:
I (115) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (120) heap_init: At 3FFB4050 len 0002BFB0 (175 KiB): DRAM
I (126) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (131) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (136) heap_init: At 40088740 len 000178C0 (94 KiB): IRAM
I (142) cpu_start: Pro cpu start user code
I (12) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (0) FATFS: Mounting FAT partition...
W (3) vfs_fat_spiflash: f_mount failed (13)
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff at 0x400d35c2
file: "/home/zhaokeke/esp/program/filesystem/ESP32_mkfatfs/main/./FATFS_VFS.cpp" line 49
func: void FATFS_VFS::mount()
expression: esp_vfs_fat_spiflash_mount(m_mountPath.c_str(), m_partitionName.c_str(), &mountConfig, &m_wl_handle)

Backtrace: 0x40086c20:0x3ffb97c0 0x40086f95:0x3ffb97e0 0x400d35c2:0x3ffb9800 0x400d3212:0x3ffb9830 0x400d351e:0x3ffb9950

CPU halted.`

**Comment by jkearins** [comment]
1) I added verification: after writing files I read files and compare their contents with origin files. Verificaton is ok. 
2) Wear-level system shuffles some sectors around, so it is not correct to mount fatfs
3) Can you turn on debug level in menuconfig to locate mount error?

**Comment by Jacques-Zhao** [comment]
Sorry for replying so late. I found that i used it in wrong way. When I change the config value WL_SECTOR_SIZE to 512, i can mount correct. Thank you very much, I will close the issue :-)
